import { supabase } from './supabase';

export type Season = {
  id: string; season_year: number; name: string | null; is_current: boolean; created_at: string;
};
export type Game = {
  id: string; season_id: string; opponent: string; game_date: string; location: string | null; my_score: number | null; opponent_score: number | null; game_result: string | null; status: string; notes: string | null; archived: boolean; created_at: string; updated_at: string;
};
export type LivePlay = {
  id: string; game_id: string; play_number: number; odk: string | null; down: number | null; dist: number | null; hash: string | null; gnls: number | null; yard_line: number | null; play_type: string | null; result: string | null; off_formation: string | null; personnel: string | null; scheme: string | null; motion: string | null; off_play: string | null; ball_carrier: string | null; defense: string | null; play_dir: string | null; backfield: string | null; created_at: string; updated_at?: string; updated_by?: string | null;
};
export type LivePlayDraft = {
  game_id: string; play_number: number; odk: string | null; down: number | null; dist: number | null; hash: string | null; yard_line: number | null; starting_yard_line: number | null; play_type: string | null; result: string | null; off_formation: string | null; off_play: string | null; ball_carrier: string | null; defense: string | null; gnls: number | null; updated_at: string; updated_by: string | null;
};
export type ScoutingSession = {
  id: string; season_id: string; game_id: string | null; opponent: string; week: number | null; description: string | null; archived: boolean; uploaded_at: string | null; created_at: string;
};
export type ScoutingPlay = {
  id: string; scouting_session_id: string; play_no: number; odk: string; dn: number | null; dist: number | null; hash: string | null; gnls: number | null; yard_ln: number | null; play_type: string; result: string | null; off_form: string | null; personnel: string | null; scheme: string | null; motion: string | null; off_play: string | null; ball_carrier: string | null; defense: string | null; rpo: string | null; direction: string | null; stunt: string | null; coverage: string | null; blitz: string | null; backfield: string | null; protection: string | null; created_at: string;
};
export type StandardPlay = {
  playNo: string; odk: string; dn: string; dist: string; hash: string; gnls: string; carrier: string; yardLn: string; type: string; result: string; form: string; personnel: string; scheme: string; defense: string; motion: string; offPlay: string; dir: string; backfield: string;
  rpo?: string; stunt?: string; coverage?: string; blitz?: string; protection?: string; read?: string; comments?: string; playStrength?: string; defCall?: string;
};

export function livePlayToStandard(play: LivePlay): StandardPlay {
  return { playNo: String(play.play_number ?? '1').padStart(2, '0'), odk: play.odk ?? 'O', dn: play.down !== null ? String(play.down) : '1', dist: play.dist !== null ? String(play.dist) : '10', hash: play.hash ?? 'M', gnls: play.gnls !== null ? String(play.gnls) : '0', carrier: play.ball_carrier ?? '—', yardLn: play.yard_line !== null ? String(play.yard_line) : '—', type: play.play_type ?? 'Run', result: play.result ?? '—', form: play.off_formation ?? '—', personnel: play.personnel ?? '—', scheme: play.scheme ?? '—', defense: play.defense ?? '—', motion: play.motion ?? 'None', offPlay: play.off_play ?? '—', dir: play.play_dir ?? '—', backfield: play.backfield ?? '—' };
}
export function scoutingPlayToStandard(play: ScoutingPlay): StandardPlay {
  return { playNo: String(play.play_no ?? '1').padStart(2, '0'), odk: play.odk ?? 'O', dn: play.dn !== null ? String(play.dn) : '1', dist: play.dist !== null ? String(play.dist) : '10', hash: play.hash ?? 'M', gnls: play.gnls !== null ? String(play.gnls) : '0', carrier: play.ball_carrier ?? '—', yardLn: play.yard_ln !== null ? String(play.yard_ln) : '—', type: play.play_type ?? 'Run', result: play.result ?? '—', form: play.off_form ?? '—', personnel: play.personnel ?? '—', scheme: play.scheme ?? '—', defense: play.defense ?? '—', motion: play.motion ?? 'None', offPlay: play.off_play ?? '—', dir: play.direction ?? '—', backfield: play.backfield ?? '—', rpo: play.rpo ?? '', stunt: play.stunt ?? '', coverage: play.coverage ?? '', blitz: play.blitz ?? '', protection: play.protection ?? '' };
}
export async function getSeasons(): Promise<Season[]> { if (!supabase) return []; const { data, error } = await supabase.from('seasons').select('*').order('season_year', { ascending: false }); if (error) throw error; return data ?? []; }
export async function getGames(seasonId?: string, includeArchived = true): Promise<Game[]> { if (!supabase) return []; let query = supabase.from('games').select('*').order('game_date', { ascending: false }); if (seasonId) query = query.eq('season_id', seasonId); if (!includeArchived) query = query.eq('archived', false); const { data, error } = await query; if (error) throw error; return data ?? []; }
export async function createGame(input: { seasonId: string; opponent: string; gameDate?: string; location?: string; result?: string }): Promise<Game | null> { if (!supabase) return null; const { data, error } = await supabase.from('games').insert({ season_id: input.seasonId, opponent: input.opponent, game_date: input.gameDate || null, location: input.location || null, game_result: input.result && input.result !== '—' ? input.result : null, archived: false }).select('*').single(); if (error) throw error; return data; }
export async function setGameArchived(gameId: string, archived: boolean): Promise<Game | null> { if (!supabase) return null; const { data, error } = await supabase.from('games').update({ archived }).eq('id', gameId).select('*').single(); if (error) throw error; return data; }
export async function getGame(gameId: string): Promise<Game | null> { if (!supabase) return null; const { data, error } = await supabase.from('games').select('*').eq('id', gameId).maybeSingle(); if (error) throw error; return data; }
export async function getLivePlays(gameId: string): Promise<LivePlay[]> { if (!supabase) return []; const { data, error } = await supabase.from('plays').select('*').eq('game_id', gameId).order('play_number', { ascending: true }); if (error) throw error; return data ?? []; }
export async function createLivePlay(gameId: string, play: StandardPlay): Promise<LivePlay | null> { if (!supabase || !gameId) return null; const row = { game_id: gameId, play_number: Number(play.playNo) || 1, odk: play.odk || null, down: Number(play.dn) || null, dist: Number(play.dist) || null, hash: play.hash || null, gnls: Number(play.gnls) || 0, yard_line: Number(String(play.yardLn).replace(/[^0-9-]/g, '')) || null, play_type: play.type || null, result: play.result || null, off_formation: play.form || null, personnel: play.personnel || null, scheme: play.scheme || null, motion: play.motion || null, off_play: play.offPlay || null, ball_carrier: play.carrier || null, defense: play.defense || null, play_dir: play.dir || null, backfield: play.backfield || null }; const { data, error } = await supabase.from('plays').insert(row).select('*').single(); if (error) throw error; return data; }
export async function updateLivePlay(playId: string, field: string, value: string): Promise<LivePlay | null> { if (!supabase || !playId) return null; const map: Record<string, string> = { odk:'odk', dn:'down', dist:'dist', hash:'hash', yardLn:'yard_line', type:'play_type', result:'result', form:'off_formation', offPlay:'off_play', carrier:'ball_carrier', defense:'defense' }; const column = map[field]; if (!column) return null; const numeric = ['down','dist','yard_line'].includes(column); const { data, error } = await supabase.from('plays').update({ [column]: numeric ? (Number(String(value).replace(/[^0-9-]/g, '')) || null) : value }).eq('id', playId).select('*').single(); if (error) throw error; return data; }

const draftNumber = (value: unknown, fallback: number | null = null) => { const n = Number(value); return Number.isFinite(n) && n !== 0 ? n : fallback; };
export async function getLivePlayDraft(gameId: string): Promise<LivePlayDraft | null> { if (!supabase || !gameId) return null; const { data, error } = await supabase.from('live_play_drafts').select('*').eq('game_id', gameId).maybeSingle(); if (error) throw error; return data ?? null; }
export async function upsertLivePlayDraft(gameId: string, play: Partial<StandardPlay> & { startingYardLine?: string }, updatedBy?: string): Promise<LivePlayDraft | null> {
  if (!supabase || !gameId) return null;
  const row: Record<string, unknown> = { game_id: gameId, play_number: draftNumber(play.playNo, 1), updated_by: updatedBy ?? null };
  const map: Record<string, string> = { odk:'odk', dn:'down', dist:'dist', hash:'hash', yardLn:'yard_line', type:'play_type', result:'result', form:'off_formation', offPlay:'off_play', carrier:'ball_carrier', defense:'defense', gnls:'gnls' };
  for (const [key, column] of Object.entries(map)) {
    if (Object.prototype.hasOwnProperty.call(play, key)) {
      const value = (play as Record<string, unknown>)[key];
      if (['down','dist','yardLn','gnls'].includes(key)) row[column] = draftNumber(value);
      else row[column] = value === '' || value === '—' ? null : value;
    }
  }
  if (Object.prototype.hasOwnProperty.call(play, 'startingYardLine')) row.starting_yard_line = draftNumber(play.startingYardLine);
  const { data, error } = await supabase.from('live_play_drafts').upsert(row, { onConflict: 'game_id' }).select('*').single();
  if (error) throw error;
  return data;
}
export async function clearLivePlayDraft(gameId: string): Promise<void> { if (!supabase || !gameId) return; const { error } = await supabase.from('live_play_drafts').delete().eq('game_id', gameId); if (error) throw error; }
export function liveDraftToStandard(draft: LivePlayDraft, previousYardLine = ''): StandardPlay {
  return { playNo: String(draft.play_number ?? 1).padStart(2, '0'), odk: draft.odk ?? '', dn: draft.down !== null ? String(draft.down) : '', dist: draft.dist !== null ? String(draft.dist) : '', hash: draft.hash ?? '', gnls: draft.gnls !== null ? String(draft.gnls) : '0', carrier: draft.ball_carrier ?? '', yardLn: draft.yard_line !== null ? String(draft.yard_line) : previousYardLine, type: draft.play_type ?? '', result: draft.result ?? '', form: draft.off_formation ?? '', personnel: '', scheme: '', defense: draft.defense ?? '', motion: '', offPlay: draft.off_play ?? '', dir: '', backfield: '' };
}
export async function getScoutingSessions(seasonId: string): Promise<ScoutingSession[]> { if (!supabase) return []; const { data, error } = await supabase.from('scouting_sessions').select('*').eq('season_id', seasonId).eq('archived', false).order('created_at', { ascending: false }); if (error) throw error; return data ?? []; }
export async function getScoutingPlays(sessionId: string): Promise<ScoutingPlay[]> { if (!supabase) return []; const { data, error } = await supabase.from('scouting_plays').select('*').eq('scouting_session_id', sessionId).order('play_no', { ascending: true }); if (error) throw error; return data ?? []; }
export async function createScoutingSession(input: { seasonId: string; team: string; description: string }): Promise<ScoutingSession | null> { if (!supabase) return null; const id = crypto.randomUUID(); const { error } = await supabase.from('scouting_sessions').insert({ id, season_id: input.seasonId, opponent: input.team.trim(), description: input.description || 'Scout File', archived: false }); if (error) throw error; const { data, error: readError } = await supabase.from('scouting_sessions').select('*').eq('id', id).maybeSingle(); if (readError) throw readError; if (!data) throw new Error('Scout File was created but could not be read back from Supabase.'); return data; }
export async function appendScoutingPlays(sessionId: string, plays: StandardPlay[]): Promise<ScoutingPlay[]> { if (!supabase || !plays.length) return []; const rows = plays.map((play, index) => ({ scouting_session_id: sessionId, play_no: Number(play.playNo) || index + 1, odk: ['O','D','K'].includes(play.odk?.toUpperCase()) ? play.odk.toUpperCase() : 'O', dn: Number(play.dn) || null, dist: Number(play.dist) || null, hash: ['L','R','M'].includes(play.hash?.toUpperCase()) ? play.hash.toUpperCase() : 'M', gnls: Number(play.gnls) || 0, yard_ln: Number.isFinite(Number(String(play.yardLn).replace(/[^0-9-]/g, ''))) ? Number(String(play.yardLn).replace(/[^0-9-]/g, '')) : null, play_type: play.type?.toUpperCase() === 'PASS' ? 'PASS' : 'RUN', result: play.result && play.result !== '—' ? play.result : null, off_form: play.form || null, personnel: play.personnel || null, scheme: play.scheme || null, motion: play.motion || null, off_play: play.offPlay || null, ball_carrier: play.carrier || null, defense: play.defense || null, rpo: play.rpo || null, direction: play.dir || null, stunt: play.stunt || null, coverage: play.coverage || null, blitz: play.blitz || null, backfield: play.backfield || null, protection: play.protection || null })); const { error } = await supabase.from('scouting_plays').insert(rows); if (error) throw error; const { data, error: readError } = await supabase.from('scouting_plays').select('*').eq('scouting_session_id', sessionId).order('play_no', { ascending: true }); if (readError) throw readError; return data ?? []; }
