import { Download, Shield, Zap, BarChart3 } from 'lucide-react';
import type { StandardPlay } from './lib/footballData';

export type ReportsDataset = { scouting: StandardPlay[]; live: StandardPlay[] };
type Props = { data: ReportsDataset };
type StatRow = { name: string; carries: number; rushYds: number; rushTd: number; receptions: number; recYds: number; recTd: number; fumbles: number };

const num = (value: string) => { const match = String(value ?? '').match(/-?\d+(?:\.\d+)?/); return match ? Number(match[0]) : 0; };
const pct = (a: number, b: number) => b ? `${Math.round((a / b) * 100)}%` : '—';
const avg = (yards: number, attempts: number) => attempts ? (yards / attempts).toFixed(1) : '0.0';
const normalizeOdk = (value: string) => { const v = String(value ?? '').trim().toLowerCase(); if (v === 'o' || v.includes('off')) return 'O'; if (v === 'd' || v.includes('def')) return 'D'; if (v === 'k' || v.includes('kick')) return 'K'; return String(value ?? '').trim().toUpperCase(); };
const isRun = (p: StandardPlay) => String(p.type).toLowerCase().includes('run');
const isPass = (p: StandardPlay) => String(p.type).toLowerCase().includes('pass');
const gain = (p: StandardPlay) => num(p.gnls);
const result = (p: StandardPlay) => String(p.result ?? '').toLowerCase();
const isTD = (p: StandardPlay) => /touchdown|\btd\b/.test(result(p));
const isFumble = (p: StandardPlay) => /fumble/.test(result(p));
const isInterception = (p: StandardPlay) => /interception|\bint\b/.test(result(p));
const isSack = (p: StandardPlay) => /sack/.test(result(p));
const isComplete = (p: StandardPlay) => /complete/.test(result(p)) && !/incomplete/.test(result(p));
const isIncomplete = (p: StandardPlay) => /incomplete/.test(result(p));
const isFirstDown = (p: StandardPlay) => { if (/first\s*down|1st\s*down|\bfd\b/.test(result(p))) return true; if (isSack(p) || isIncomplete(p) || isInterception(p)) return false; const d = num(p.dn); const dist = num(p.dist); return d >= 1 && d <= 4 && dist > 0 && gain(p) >= dist; };
const explosiveRun = (p: StandardPlay) => isRun(p) && gain(p) >= 10;
const explosivePass = (p: StandardPlay) => isPass(p) && gain(p) >= 15;
const explosive = (p: StandardPlay) => explosiveRun(p) || explosivePass(p);

function Panel({ children, className = '', pad = true }: { children: React.ReactNode; className?: string; pad?: boolean }) { return <section className={`panel ${pad ? 'panel-pad' : ''} ${className}`}>{children}</section>; }
function SectionTitle({ title, detail }: { title: string; detail?: string }) { return <div className="section-title"><div><h2>{title}</h2>{detail && <p>{detail}</p>}</div></div>; }
function Kpi({ label, value, note, green = false }: { label: string; value: string; note?: string; green?: boolean }) { return <div className="panel kpi"><div className="kpi-label">{label}</div><div className="kpi-value" style={green ? { color: '#62dfae' } : undefined}>{value}</div>{note && <div className="kpi-note">{note}</div>}</div>; }
function empty(message: string) { return <div className="empty" style={{ padding: 22 }}><BarChart3 size={24} /><p style={{ margin: 0 }}>{message}</p></div>; }
function runPass(plays: StandardPlay[]) { const runs = plays.filter(isRun).length; const passes = plays.filter(isPass).length; return plays.length ? `${pct(runs, plays.length)} / ${pct(passes, plays.length)}` : '—'; }
function situation(play: StandardPlay) { const d = num(play.dn); const dist = num(play.dist); if (d === 1) return '1st & long'; const down = d === 2 ? '2nd' : d === 3 ? '3rd' : `${d}th`; return `${down} & ${dist >= 7 ? 'long' : dist >= 4 ? 'medium' : 'short'}`; }
function buildStats(plays: StandardPlay[]): StatRow[] { const by = new Map<string, StatRow>(); for (const play of plays) { const name = String(play.carrier ?? '').trim(); if (!name || name === '—') continue; const row = by.get(name) ?? { name, carries: 0, rushYds: 0, rushTd: 0, receptions: 0, recYds: 0, recTd: 0, fumbles: 0 }; if (isRun(play) || isFumble(play) && !isPass(play)) { row.carries += 1; row.rushYds += gain(play); if (isTD(play)) row.rushTd += 1; } if (isPass(play) && isComplete(play)) { row.receptions += 1; row.recYds += gain(play); if (isTD(play)) row.recTd += 1; } if (isFumble(play)) row.fumbles += 1; by.set(name, row); } return [...by.values()].filter(row => row.carries || row.receptions).sort((a, b) => (b.rushYds + b.recYds) - (a.rushYds + a.recYds)); }
function csvCell(value: string) { return `"${String(value ?? '').replaceAll('"', '""')}"`; }
function download(name: string, contents: string) { const blob = new Blob([contents], { type: 'text/csv;charset=utf-8' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = name; link.click(); URL.revokeObjectURL(url); }

function OffenseReport({ live, scoutDefense }: { live: StandardPlay[]; scoutDefense: StandardPlay[] }) {
  const runs = live.filter(isRun); const passes = live.filter(isPass); const stats = buildStats(live);
  const formations = [...new Set(live.map(p => p.form).filter(Boolean))].map(form => { const rows = live.filter(p => p.form === form); const call = [...new Set(rows.map(p => p.offPlay).filter(Boolean))].map(call => ({ call, count: rows.filter(p => p.offPlay === call).length })).sort((a,b)=>b.count-a.count)[0]?.call ?? '—'; return { form, count: rows.length, run: pct(rows.filter(isRun).length, rows.length), pass: pct(rows.filter(isPass).length, rows.length), call }; }).sort((a,b)=>b.count-a.count).slice(0, 8);
  const calls = (kind: 'run' | 'pass') => [...new Set(live.filter(kind === 'run' ? isRun : isPass).map(p => p.offPlay).filter(Boolean))].map(call => { const rows = live.filter(p => p.offPlay === call && (kind === 'run' ? isRun(p) : isPass(p))); const yards = rows.reduce((sum,p)=>sum+gain(p),0); return { call, count: rows.length, avg: avg(yards, rows.length), explosive: rows.filter(kind === 'run' ? explosiveRun : explosivePass).length }; }).sort((a,b)=>b.count-a.count).slice(0, 10);
  const situations = ['1st & long','2nd & long','2nd & medium','2nd & short','3rd & long','3rd & medium','3rd & short'];
  return <div className="grid">
    <Panel><SectionTitle title="OUR OFFENSE · LIVE" detail="Live ODK = O. This is our offense, not the opponent's." /><div className="grid kpi-grid"><Kpi label="Plays" value={String(live.length)} /><Kpi label="Run / Pass" value={`${pct(runs.length,live.length)} / ${pct(passes.length,live.length)}`} /><Kpi label="Yards / play" value={avg(live.reduce((s,p)=>s+gain(p),0),live.length)} green /><Kpi label="Explosives" value={String(live.filter(explosive).length)} note="10+ run / 15+ pass" green /></div></Panel>
    <Panel><SectionTitle title="SCOUT → GAME-DAY MATCHUP" detail="Opponent defense from scouting vs our live offense" /><div className="comparison"><div className="compare-col"><div className="compare-head"><strong>Opponent defense · scout</strong><span className="tag">baseline</span></div><div className="compare-stat"><span>Snaps</span><b>{scoutDefense.length}</b></div><div className="compare-stat"><span>Run / pass</span><b>{runPass(scoutDefense)}</b></div><div className="compare-stat"><span>Avg gain</span><b>{avg(scoutDefense.reduce((s,p)=>s+gain(p),0),scoutDefense.length)}</b></div></div><div className="compare-col"><div className="compare-head"><strong>Our offense · live</strong><span className="tag green">today</span></div><div className="compare-stat"><span>Snaps</span><b>{live.length}</b></div><div className="compare-stat"><span>Run / pass</span><b>{runPass(live)}</b></div><div className="compare-stat"><span>Avg gain</span><b>{avg(live.reduce((s,p)=>s+gain(p),0),live.length)}</b></div></div></div></Panel>
    <Panel><SectionTitle title="Top formations" detail="Our live offensive identity" />{formations.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>Formation</th><th>Snaps</th><th>R%</th><th>P%</th><th>Favorite call</th></tr></thead><tbody>{formations.map(row=><tr key={row.form}><td><strong>{row.form}</strong></td><td>{row.count}</td><td>{row.run}</td><td>{row.pass}</td><td>{row.call}</td></tr>)}</tbody></table></div> : empty('No live O formations yet.')}</Panel>
    <div className="grid split-grid"><Panel><SectionTitle title="Top run plays" />{calls('run').length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>Play</th><th>Calls</th><th>Avg</th><th>X</th></tr></thead><tbody>{calls('run').map(row=><tr key={row.call}><td><strong>{row.call}</strong></td><td>{row.count}</td><td>{row.avg}</td><td>{row.explosive}</td></tr>)}</tbody></table></div> : empty('No live run calls yet.')}</Panel><Panel><SectionTitle title="Top pass plays" />{calls('pass').length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>Play</th><th>Calls</th><th>Avg</th><th>X</th></tr></thead><tbody>{calls('pass').map(row=><tr key={row.call}><td><strong>{row.call}</strong></td><td>{row.count}</td><td>{row.avg}</td><td>{row.explosive}</td></tr>)}</tbody></table></div> : empty('No live pass calls yet.')}</Panel></div>
    <Panel><SectionTitle title="Down & distance" detail="Our live ODK = O compared with opponent D scouting baseline" /><div className="table-wrap"><table className="data-table"><thead><tr><th>Situation</th><th>Opponent D · scout</th><th>Our O · live</th></tr></thead><tbody>{situations.map(label=><tr key={label}><td><strong>{label}</strong></td><td>{runPass(scoutDefense.filter(p=>situation(p)===label))}</td><td>{runPass(live.filter(p=>situation(p)===label))}</td></tr>)}</tbody></table></div></Panel>
    <Panel><SectionTitle title="Our ball carrier / receiver stats" />{stats.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>Player</th><th>Car</th><th>Rush Yds</th><th>YPC</th><th>Rush TD</th><th>Rec</th><th>Rec Yds</th><th>Rec TD</th><th>Fum</th></tr></thead><tbody>{stats.map(row=><tr key={row.name}><td><strong>{row.name}</strong></td><td>{row.carries}</td><td>{row.rushYds}</td><td>{avg(row.rushYds,row.carries)}</td><td>{row.rushTd}</td><td>{row.receptions}</td><td>{row.recYds}</td><td>{row.recTd}</td><td>{row.fumbles}</td></tr>)}</tbody></table></div> : empty('No named live ball carrier / receiver stats yet.')}</Panel>
  </div>;
}

function DefenseReport({ live, scoutOffense }: { live: StandardPlay[]; scoutOffense: StandardPlay[] }) {
  const formations = [...new Set([...scoutOffense, ...live].map(p => p.form).filter(Boolean))].slice(0, 10); const situations = ['1st & long','2nd & long','2nd & medium','2nd & short','3rd & long','3rd & medium','3rd & short']; const allowedYards = live.reduce((sum,p)=>sum+gain(p),0); const third = live.filter(p => num(p.dn) === 3); const thirdStops = third.filter(p => !isFirstDown(p)).length; const explosiveAllowed = live.filter(explosive).length;
  return <div className="grid">
    <Panel><SectionTitle title="OUR DEFENSE · LIVE" detail="Live ODK = D. This is our defense, not the opponent's defense." /><div className="grid kpi-grid"><Kpi label="Defensive snaps" value={String(live.length)} /><Kpi label="Run / Pass allowed" value={runPass(live)} /><Kpi label="Yards allowed" value={String(allowedYards)} /><Kpi label="3rd down stop" value={pct(thirdStops,third.length)} green /></div></Panel>
    <Panel><SectionTitle title="SCOUT → GAME-DAY MATCHUP" detail="Opponent offense from scouting vs our live defense" /><div className="comparison"><div className="compare-col"><div className="compare-head"><strong>Opponent offense · scout</strong><span className="tag">baseline</span></div><div className="compare-stat"><span>Snaps</span><b>{scoutOffense.length}</b></div><div className="compare-stat"><span>Run / pass</span><b>{runPass(scoutOffense)}</b></div><div className="compare-stat"><span>Avg gain</span><b>{avg(scoutOffense.reduce((s,p)=>s+gain(p),0),scoutOffense.length)}</b></div></div><div className="compare-col"><div className="compare-head"><strong>Our defense · live</strong><span className="tag green">today</span></div><div className="compare-stat"><span>Snaps</span><b>{live.length}</b></div><div className="compare-stat"><span>Run / pass</span><b>{runPass(live)}</b></div><div className="compare-stat"><span>Avg gain allowed</span><b>{avg(allowedYards,live.length)}</b></div></div></div></Panel>
    <Panel><SectionTitle title="Down & distance defense" detail="Opponent offense scout vs our defense live" /><div className="table-wrap"><table className="data-table"><thead><tr><th>Situation</th><th>Opponent O · scout</th><th>Our D · live</th></tr></thead><tbody>{situations.map(label=><tr key={label}><td><strong>{label}</strong></td><td>{runPass(scoutOffense.filter(p=>situation(p)===label))}</td><td>{runPass(live.filter(p=>situation(p)===label))}</td></tr>)}</tbody></table></div></Panel>
    <Panel><SectionTitle title="Formation tendencies" detail="What the opponent showed vs what our defense saw live" />{formations.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>Formation</th><th>Opponent O · scout</th><th>Our D · live</th></tr></thead><tbody>{formations.map(form=><tr key={form}><td><strong>{form}</strong></td><td>{runPass(scoutOffense.filter(p=>p.form===form))}</td><td>{runPass(live.filter(p=>p.form===form))}</td></tr>)}</tbody></table></div> : empty('No defensive formation data yet.')}</Panel>
    <Panel><SectionTitle title="Defensive flags" detail="Immediate game-day checks" /><div className="grid kpi-grid"><Kpi label="Explosives allowed" value={String(explosiveAllowed)} note="10+ run / 15+ pass" /><Kpi label="1st downs allowed" value={String(live.filter(isFirstDown).length)} /><Kpi label="INT" value={String(live.filter(isInterception).length)} green /><Kpi label="Fumbles" value={String(live.filter(isFumble).length)} /></div></Panel>
    <Panel><SectionTitle title="Recent defensive snaps" />{live.length ? <div className="table-wrap"><table className="data-table"><thead><tr><th>Play</th><th>Situation</th><th>Type</th><th>Formation</th><th>Gain / loss</th><th>Result</th></tr></thead><tbody>{live.slice(-12).reverse().map((p,i)=><tr key={`${p.playNo}-${i}`}><td><strong>#{p.playNo}</strong></td><td>{p.dn}&amp;{p.dist}</td><td>{p.type}</td><td>{p.form}</td><td>{gain(p)>0?`+${gain(p)}`:gain(p)}</td><td>{p.result}</td></tr>)}</tbody></table></div> : empty('No live D entries yet.')}</Panel>
  </div>;
}

export default function ReportsHubPage({ data }: Props) {
  const [active, setActive] = useState<'offense' | 'defense'>('offense'); const live = Array.isArray(data?.live) ? data.live : []; const scouting = Array.isArray(data?.scouting) ? data.scouting : [];
  const ourOffense = live.filter(p => normalizeOdk(p.odk) === 'O'); const ourDefense = live.filter(p => normalizeOdk(p.odk) === 'D');
  const opponentDefense = scouting.filter(p => normalizeOdk(p.odk) === 'D'); const opponentOffense = scouting.filter(p => normalizeOdk(p.odk) === 'O');
  const exportReport = () => { const source = active === 'offense' ? ourOffense : ourDefense; const headers = ['Play #','ODK','Down','Distance','Type','Formation','Play Call','Ball Carrier','Gain/Loss','Result','Yard Line']; const rows = source.map(p => [p.playNo,p.odk,p.dn,p.dist,p.type,p.form,p.offPlay,p.carrier,p.gnls,p.result,p.yardLn].map(csvCell).join(',')); download(`coach-hudl-live-${active}.csv`, [headers.join(','), ...rows].join('\n')); };
  return <div className="content">
    <div className="page-head fade-in"><div><div className="eyebrow">Reports · game-day perspective</div><h1>Make the call.</h1><p>Reports use the live game board from our perspective. <strong>O = our offense.</strong> <strong>D = our defense.</strong> Scouting stays in opponent perspective for the matchup comparison.</p></div><div className="actions"><button className="btn btn-primary" onClick={exportReport}><Download /> Export {active} CSV</button></div></div>
    <div className="filters report-tabs"><button className={`btn ${active==='offense'?'btn-green':'btn-ghost'}`} onClick={()=>setActive('offense')}><Zap /> Our offense · O</button><button className={`btn ${active==='defense'?'btn-primary':'btn-ghost'}`} onClick={()=>setActive('defense')}><Shield /> Our defense · D</button><span className="eyebrow">{active==='offense'?ourOffense.length:ourDefense.length} live snaps in view</span></div>
    <Panel><SectionTitle title="Perspective" detail="This is the important distinction for game day." /><div className="grid kpi-grid"><Kpi label="Our offense" value={`O · ${ourOffense.length}`} note="Live game" green /><Kpi label="Our defense" value={`D · ${ourDefense.length}`} note="Live game" /><Kpi label="Opponent offense" value={`O · ${opponentOffense.length}`} note="Scouting baseline" /><Kpi label="Opponent defense" value={`D · ${opponentDefense.length}`} note="Scouting baseline" /></div></Panel>
    {active==='offense' ? <OffenseReport live={ourOffense} scoutDefense={opponentDefense} /> : <DefenseReport live={ourDefense} scoutOffense={opponentOffense} />}
  </div>;
}
