import { type CSSProperties, type ReactNode, useMemo, useState } from 'react';
import { Activity, Download, Printer, Search, TrendingUp, Target, X, Zap } from 'lucide-react';
import type { StandardPlay } from './lib/footballData';

type Play = StandardPlay;
const n = (v: string) => { const m = String(v ?? '').match(/-?\d+/); return m ? Number(m[0]) : 0; };
const pct = (a: number, b: number) => b ? Math.round((a / b) * 100) : 0;
const avg = (plays: Play[]) => plays.length ? (plays.reduce((s, p) => s + n(p.gnls), 0) / plays.length).toFixed(1) : '0.0';
const isRun = (p: Play) => p.type.toLowerCase().includes('run');
const isPass = (p: Play) => p.type.toLowerCase().includes('pass');
const clean = (v: string) => v && v !== '—' ? v : 'Unclassified';

function Card({ children, title, detail, className = '', style }: { children: ReactNode; title?: string; detail?: string; className?: string; style?: CSSProperties }) {
  return <section className={`panel ${className}`} style={style}>
    {title && <div style={{ padding: '21px 21px 0' }}><div className="section-title"><div><h3>{title}</h3>{detail && <span>{detail}</span>}</div></div></div>}
    <div style={{ padding: title ? '14px 21px 21px' : 21 }}>{children}</div>
  </section>;
}
function Bar({ label, value, total, green = false }: { label: string; value: number; total: number; green?: boolean }) {
  const width = pct(value, total);
  return <div className="trend-row"><div className="trend-head"><span>{label}</span><strong>{value} <small>({width}%)</small></strong></div><div className={`progress ${green ? 'green' : ''}`}><span style={{ width: `${width}%` }} /></div></div>;
}
function Slide({ number, title, subtitle, children }: { number: number; title: string; subtitle?: string; children: ReactNode }) {
  return <section className="scout-slide" data-slide={number}>
    <div className="scout-slide-top"><span>COACH HUDL · SCOUTING</span><span>{String(number).padStart(2, '0')}</span></div>
    <div className="scout-slide-title"><div><div className="eyebrow">OPPONENT INTELLIGENCE</div><h2>{title}</h2>{subtitle && <p>{subtitle}</p>}</div></div>
    <div className="scout-slide-body">{children}</div>
    <div className="scout-slide-footer"><span>Prepared from selected Scout File</span><span>CONFIDENTIAL · COACHING STAFF</span></div>
  </section>;
}
function Metric({ label, value, note }: { label: string; value: string | number; note?: string }) {
  return <div className="scout-slide-metric"><span>{label}</span><strong>{value}</strong>{note && <small>{note}</small>}</div>;
}
function MiniTable({ rows, headers }: { rows: string[][]; headers: string[] }) {
  return <table className="data-table scout-slide-table"><thead><tr>{headers.map(h => <th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((row, i) => <tr key={i}>{row.map((cell, j) => <td key={j}>{j === 0 ? <strong>{cell}</strong> : cell}</td>)}</tr>)}</tbody></table>;
}

export default function ScoutDashboard({ data }: { data: { scouting: Play[]; schedule?: { opponent: string; season: string; date: string }[]; activeGameId?: string } }) {
  const [search, setSearch] = useState(''); const [typeFilter, setTypeFilter] = useState('All'); const [formationFilter, setFormationFilter] = useState('All'); const [slidesOpen, setSlidesOpen] = useState(false);
  const source = data.scouting ?? [];
  const activeGame = data.schedule?.find(g => g.date) ?? data.schedule?.[0];
  const opponent = activeGame?.opponent ?? 'Selected Opponent';
  const formations = useMemo(() => Array.from(new Set(source.map(p => clean(p.form)))).sort((a,b) => a.localeCompare(b)), [source]);
  const filtered = useMemo(() => source.filter(p => { const text = Object.values(p).join(' ').toLowerCase(); return (typeFilter === 'All' || (typeFilter === 'Run' ? isRun(p) : isPass(p))) && (formationFilter === 'All' || clean(p.form) === formationFilter) && text.includes(search.toLowerCase()); }), [source, search, typeFilter, formationFilter]);
  const runs = filtered.filter(isRun); const passes = filtered.filter(isPass); const explosive = filtered.filter(p => n(p.gnls) >= 12); const success = filtered.filter(p => { const d = n(p.dn), dist = Math.max(n(p.dist), 1), gain = n(p.gnls); if (d === 1) return gain >= 4 || gain >= dist * .4; if (d === 2) return gain >= dist * .6 || gain >= 4; return gain >= dist; }); const motions = filtered.filter(p => clean(p.motion).toLowerCase() !== 'none' && clean(p.motion).toLowerCase() !== 'unclassified');
  const formationStats = useMemo(() => formations.map(form => { const ps = filtered.filter(p => clean(p.form) === form); const r = ps.filter(isRun); const calls = Array.from(new Set(ps.map(p => clean(p.offPlay)))).map(call => ({ call, count: ps.filter(p => clean(p.offPlay) === call).length })).sort((a,b) => b.count-a.count); return { form, total: ps.length, runs: r.length, passes: ps.length-r.length, avg: avg(ps), topCall: calls[0]?.call ?? '—', topCallCount: calls[0]?.count ?? 0 }; }).filter(x => x.total).sort((a,b) => b.total-a.total), [formations, filtered]);
  const downBuckets = [['1st & 10+', (p: Play) => p.dn === '1' && n(p.dist) >= 10], ['1st & Short', (p: Play) => p.dn === '1' && n(p.dist) < 10], ['2nd & Long', (p: Play) => p.dn === '2' && n(p.dist) >= 8], ['2nd & Medium', (p: Play) => p.dn === '2' && n(p.dist) >= 4 && n(p.dist) < 8], ['2nd & Short', (p: Play) => p.dn === '2' && n(p.dist) < 4], ['3rd & Long', (p: Play) => p.dn === '3' && n(p.dist) >= 7], ['3rd & Medium', (p: Play) => p.dn === '3' && n(p.dist) >= 3 && n(p.dist) < 7], ['3rd & Short / 4th', (p: Play) => (p.dn === '3' && n(p.dist) < 3) || p.dn === '4']] as const;
  const downStats = downBuckets.map(([label, fn]) => { const ps = filtered.filter(fn); return { label, total: ps.length, runPct: pct(ps.filter(isRun).length, ps.length), passPct: pct(ps.filter(isPass).length, ps.length), avg: avg(ps) }; }).filter(x => x.total);
  const zoneStats = [['Backed Up', (p: Play) => { const y = n(p.yardLn); return y < 0 && Math.abs(y) <= 10; }], ['Own Territory', (p: Play) => { const y = n(p.yardLn); return y < 0 && Math.abs(y) >= 11 && Math.abs(y) <= 39; }], ['Midfield', (p: Play) => { const y = n(p.yardLn); return y < 0 && Math.abs(y) >= 40 || y >= 0 && y <= 40; }], ['Red Zone', (p: Play) => { const y = n(p.yardLn); return y > 0 && y >= 11 && y <= 39; }], ['Goal Line', (p: Play) => { const y = n(p.yardLn); return y > 0 && y <= 10; }]].map(([label, fn]) => { const ps = filtered.filter(fn); return { label, total: ps.length, runPct: pct(ps.filter(isRun).length, ps.length), passPct: pct(ps.filter(isPass).length, ps.length), avg: avg(ps) }; }).filter(x => x.total);
  const topCalls = Array.from(new Set(filtered.map(p => clean(p.offPlay)))).map(call => { const ps = filtered.filter(p => clean(p.offPlay) === call); return { call, total: ps.length, runs: ps.filter(isRun).length, avg: avg(ps) }; }).sort((a,b) => b.total-a.total).slice(0,8);
  const backfieldStats = Array.from(new Set(filtered.map(p => clean(p.backfield)))).map(v => { const ps = filtered.filter(p => clean(p.backfield) === v); return { value: v, total: ps.length, runPct: pct(ps.filter(isRun).length, ps.length) }; }).sort((a,b) => b.total-a.total).slice(0,5);
  const motionStats = Array.from(new Set(filtered.map(p => clean(p.motion)).filter(v => v.toLowerCase() !== 'unclassified' && v.toLowerCase() !== 'none'))).map(v => { const ps = filtered.filter(p => clean(p.motion) === v); return { value: v, total: ps.length, runPct: pct(ps.filter(isRun).length, ps.length) }; }).sort((a,b) => b.total-a.total).slice(0,5);
  const alerts: string[] = []; if (filtered.length && pct(runs.length, filtered.length) >= 65) alerts.push(`Overall run tendency is ${pct(runs.length, filtered.length)}%.`); if (downStats.some(x => x.label === '3rd & Long' && x.passPct >= 65)) alerts.push('3rd & Long is a strong pass situation.'); const heavy = formationStats.find(x => x.total >= 3 && pct(x.runs, x.total) >= 75); if (heavy) alerts.push(`${heavy.form} is a heavy run formation (${pct(heavy.runs, heavy.total)}%).`); if (motions.length >= 3) alerts.push(`${pct(motions.filter(isRun).length, motions.length)}% run when motion is used.`); if (!alerts.length && filtered.length) alerts.push('No high-confidence automatic tells yet — keep charting.');

  return <>
    <style>{`@media print { body * { visibility:hidden !important; } .scout-print-deck, .scout-print-deck * { visibility:visible !important; } .scout-print-deck { position:absolute !important; inset:0 !important; } .scout-slide { break-after:page; page-break-after:always; } .scout-slide:last-child { break-after:auto; } @page { size: landscape; margin:0; } } .scout-print-deck{position:fixed;inset:0;z-index:1000;background:#090a0f;overflow:auto;padding:28px}.scout-slide{width:min(1120px,92vw);aspect-ratio:16/9;margin:0 auto 28px;background:linear-gradient(145deg,#11131a,#0b0d12);border:1px solid #272b36;border-radius:14px;padding:34px 42px;box-sizing:border-box;color:#f6f7fb;display:flex;flex-direction:column;box-shadow:0 18px 50px rgba(0,0,0,.35)}.scout-slide-top,.scout-slide-footer{display:flex;justify-content:space-between;font-size:10px;letter-spacing:.14em;color:#7e8494}.scout-slide-title{margin-top:26px}.scout-slide-title h2{font-size:34px;margin:5px 0 5px}.scout-slide-title p{margin:0;color:#9da3b2;font-size:13px}.scout-slide-body{flex:1;min-height:0;padding-top:18px}.scout-slide-footer{margin-top:auto;padding-top:12px;border-top:1px solid #252936}.scout-slide-metrics{display:grid;grid-template-columns:repeat(6,1fr);gap:10px}.scout-slide-metric{background:#171a22;border:1px solid #282d38;border-radius:9px;padding:15px}.scout-slide-metric span,.scout-slide-metric small{display:block;color:#8f95a5;font-size:10px;text-transform:uppercase;letter-spacing:.08em}.scout-slide-metric strong{display:block;font-size:27px;margin:7px 0}.scout-slide-grid{display:grid;grid-template-columns:1fr 1fr;gap:18px;height:100%}.scout-slide-panel{background:#14171f;border:1px solid #282d38;border-radius:9px;padding:15px;min-height:0}.scout-slide-panel h3{margin:0 0 10px;font-size:13px}.scout-slide-table{font-size:10px}.scout-slide-table th,.scout-slide-table td{padding:7px}.scout-tell{padding:11px 12px;border-left:3px solid #6ad6a8;background:#151a1c;margin-bottom:8px;font-size:12px}.scout-hero{display:flex;align-items:center;height:100%;gap:40px}.scout-hero h3{font-size:48px;margin:0}.scout-hero p{color:#9da3b2;max-width:600px;line-height:1.7}.scout-close{position:sticky;top:0;z-index:3;display:flex;justify-content:flex-end;margin-bottom:10px}.scout-slide-action{position:fixed;right:22px;bottom:22px;z-index:1002;display:flex;gap:8px}`}</style>
    <div className="content">
      <div className="page-head"><div><div className="eyebrow">SCOUTING · FULL TENDENCY DASHBOARD</div><h1>Know the tell before the snap.</h1><p>Formation, down & distance, field position and play-call tendencies from the selected Scout File.</p></div><div className="actions"><button className="btn btn-primary" onClick={() => setSlidesOpen(true)} disabled={!filtered.length}><Download /> Create Scouting Slides</button></div></div>
      <div className="filters" style={{ marginBottom: 14 }}><div style={{ position: 'relative' }}><Search size={15} style={{ position: 'absolute', left: 11, top: 10, color: '#77758a' }} /><input className="input" style={{ paddingLeft: 33, width: 230 }} placeholder="Search scout data…" value={search} onChange={e => setSearch(e.target.value)} /></div><select value={typeFilter} onChange={e => setTypeFilter(e.target.value)}><option>All</option><option>Run</option><option>Pass</option></select><select value={formationFilter} onChange={e => setFormationFilter(e.target.value)}><option>All</option>{formations.map(f => <option key={f}>{f}</option>)}</select><span className="eyebrow" style={{ marginLeft: 'auto' }}>{filtered.length} / {source.length} snaps</span></div>
      <div className="grid split-grid"><Card title="Scout snapshot" detail="Selected Scout File"><div className="kpi-grid">{[['Snaps', filtered.length], ['Run %', `${pct(runs.length, filtered.length)}%`], ['Pass %', `${pct(passes.length, filtered.length)}%`], ['Avg Yards', avg(filtered)], ['Success %', `${pct(success.length, filtered.length)}%`], ['Explosive', explosive.length]].map(([label,value]) => <div className="kpi" key={String(label)}><span>{label}</span><strong>{value}</strong></div>)}</div></Card><Card title="Run / pass profile" detail="What they want to do"><Bar label="Run calls" value={runs.length} total={filtered.length} green /><Bar label="Pass calls" value={passes.length} total={filtered.length} /></Card></div>
      <div className="grid split-grid" style={{ marginTop: 14 }}><Card title="Formation report" detail="Volume · tendency · favorite call"><div className="table-wrap"><table className="data-table"><thead><tr><th>Formation</th><th>Snaps</th><th>Run</th><th>Pass</th><th>Avg</th><th>Top call</th></tr></thead><tbody>{formationStats.slice(0,8).map(x => <tr key={x.form}><td><strong>{x.form}</strong></td><td>{x.total}</td><td>{pct(x.runs,x.total)}%</td><td>{pct(x.passes,x.total)}%</td><td>{x.avg}</td><td>{x.topCall} <small>({x.topCallCount})</small></td></tr>)}</tbody></table></div></Card><Card title="Down & distance" detail="Situational run/pass tendencies">{downStats.length ? downStats.map(x => <div className="trend-row" key={x.label}><div className="trend-head"><span>{x.label}</span><span>{x.runPct}% run · {x.passPct}% pass</span></div><div className="progress green"><span style={{ width: `${x.runPct}%` }} /></div></div>) : <div className="empty"><Target size={26}/><h3>No down/distance data</h3></div>}</Card></div>
      <div className="grid split-grid" style={{ marginTop: 14 }}><Card title="Field position" detail="Five-zone scouting model"><div className="table-wrap"><table className="data-table"><thead><tr><th>Zone</th><th>Snaps</th><th>Run</th><th>Pass</th><th>Avg</th></tr></thead><tbody>{zoneStats.map(x => <tr key={x.label}><td><strong>{x.label}</strong></td><td>{x.total}</td><td>{x.runPct}%</td><td>{x.passPct}%</td><td>{x.avg}</td></tr>)}</tbody></table></div></Card><Card title="Top play calls" detail="Highest-volume calls"><div className="feed">{topCalls.map((x,i) => <div className="feed-row" key={x.call}><span className="feed-num">{String(i+1).padStart(2,'0')}</span><div className="feed-main"><strong>{x.call}</strong><span>{x.total} snaps · {pct(x.runs,x.total)}% run · {x.avg} avg yards</span></div></div>)}</div></Card></div>
      <div className="grid split-grid" style={{ marginTop: 14 }}><Card title="Backfield & motion tells" detail="Pre-snap indicators"><div className="feed">{backfieldStats.map(x => <div className="feed-row" key={x.value}><div className="feed-main"><strong>{x.value}</strong><span>{x.total} snaps · {x.runPct}% run</span></div></div>)}{motionStats.map(x => <div className="feed-row" key={x.value}><div className="feed-main"><strong>Motion: {x.value}</strong><span>{x.total} snaps · {x.runPct}% run</span></div></div>)}</div></Card><Card title="Automatic tendency tells" detail="Signals worth carrying into the meeting"><div className="feed">{alerts.map((a,i) => <div className="feed-row" key={a}><span className="feed-num">{String(i+1).padStart(2,'0')}</span><div className="feed-main"><strong><TrendingUp size={14} style={{ verticalAlign: 'middle', marginRight: 6 }} />{a}</strong></div></div>)}</div><div className="callout"><Activity />The dashboard uses the selected Scout File only. Live Game data is intentionally excluded.</div></Card></div>
      <Card title="Scouting play ledger" detail="Filtered snap-by-snap detail" className="fade-in" style={{ marginTop: 14 }}><div className="table-wrap"><table className="data-table"><thead><tr><th>Play</th><th>Situation</th><th>Type</th><th>Formation</th><th>Call</th><th>Backfield</th><th>Motion</th><th>Gain</th><th>Defense</th></tr></thead><tbody>{filtered.slice(0,100).map((p,i)=><tr key={`${p.playNo}-${i}`}><td><strong>#{p.playNo}</strong></td><td>{p.dn}&{p.dist} · {p.hash}</td><td><span className={`tag ${isRun(p)?'green':''}`}>{p.type}</span></td><td>{clean(p.form)}</td><td>{clean(p.offPlay)}</td><td>{clean(p.backfield)}</td><td>{clean(p.motion)}</td><td>{p.gnls}</td><td>{clean(p.defense)}</td></tr>)}</tbody></table></div>{filtered.length>100 && <div className="eyebrow" style={{paddingTop:12}}>Showing first 100 rows. Use filters/search to narrow the ledger.</div>}</Card>
    </div>

    {slidesOpen && <div className="scout-print-deck">
      <div className="scout-close"><button className="btn btn-ghost" onClick={() => setSlidesOpen(false)}><X /> Close presentation</button></div>
      <Slide number={1} title={`${opponent} Scouting Report`} subtitle="Opponent intelligence · Selected Scout File"><div className="scout-hero"><div><div className="eyebrow">FULL SCOUTING PRESENTATION</div><h3>{filtered.length} snaps</h3><p>This deck is generated directly from the current Scout File and current dashboard filters. It does not include Live Game data.</p></div><Zap size={90} /></div></Slide>
      <Slide number={2} title="Performance Summary" subtitle="Core scouting metrics"><div className="scout-slide-metrics"><Metric label="Snaps" value={filtered.length}/><Metric label="Run" value={`${pct(runs.length,filtered.length)}%`} note={`${runs.length} calls`}/><Metric label="Pass" value={`${pct(passes.length,filtered.length)}%`} note={`${passes.length} calls`}/><Metric label="Avg Yards" value={avg(filtered)}/><Metric label="Success" value={`${pct(success.length,filtered.length)}%`}/><Metric label="Explosive" value={explosive.length}/></div><div className="scout-slide-grid" style={{marginTop:18}}><div className="scout-slide-panel"><h3>Identity</h3><p style={{fontSize:22,lineHeight:1.4}}>{pct(runs.length,filtered.length) >= 65 ? 'RUN-HEAVY' : pct(passes.length,filtered.length) >= 65 ? 'PASS-HEAVY' : 'BALANCED'} <span style={{color:'#9da3b2',fontSize:13}}>profile</span></p><Bar label="Run calls" value={runs.length} total={filtered.length} green/><Bar label="Pass calls" value={passes.length} total={filtered.length}/></div><div className="scout-slide-panel"><h3>Explosive plays</h3><p style={{fontSize:28,margin:'10px 0'}}>{explosive.length}</p><p style={{color:'#9da3b2'}}>Snaps gaining 12+ yards in the current chart.</p></div></div></Slide>
      <Slide number={3} title="Formation Tendencies" subtitle="Volume, run/pass identity and favorite call"><MiniTable headers={['Formation','Snaps','Run','Pass','Avg','Top Call']} rows={formationStats.slice(0,8).map(x=>[x.form,String(x.total),`${pct(x.runs,x.total)}%`,`${pct(x.passes,x.total)}%`,x.avg,`${x.topCall} (${x.topCallCount})`])}/></Slide>
      <Slide number={4} title="Down & Distance" subtitle="Situational tendencies by coaching bucket"><MiniTable headers={['Situation','Snaps','Run','Pass','Avg']} rows={downStats.map(x=>[x.label,String(x.total),`${x.runPct}%`,`${x.passPct}%`,x.avg])}/></Slide>
      <Slide number={5} title="Field Position" subtitle="Five-zone yard-line breakdown"><MiniTable headers={['Zone','Snaps','Run','Pass','Avg']} rows={zoneStats.map(x=>[x.label,String(x.total),`${x.runPct}%`,`${x.passPct}%`,x.avg])}/></Slide>
      <Slide number={6} title="Backfield & Motion Tells" subtitle="Pre-snap indicators and associated run rates"><div className="scout-slide-grid"><div className="scout-slide-panel"><h3>Backfield</h3><MiniTable headers={['Look','Snaps','Run']} rows={backfieldStats.map(x=>[x.value,String(x.total),`${x.runPct}%`])}/></div><div className="scout-slide-panel"><h3>Motion</h3><MiniTable headers={['Motion','Snaps','Run']} rows={motionStats.map(x=>[x.value,String(x.total),`${x.runPct}%`])}/></div></div></Slide>
      <Slide number={7} title="Top Concepts & Calls" subtitle="Highest-volume calls to prepare for"><MiniTable headers={['Call','Snaps','Run','Avg Yards']} rows={topCalls.map(x=>[x.call,String(x.total),`${pct(x.runs,x.total)}%`,x.avg])}/></Slide>
      <Slide number={8} title="Automated Scouting Verdict" subtitle="Signals worth carrying into the meeting"><div>{alerts.map((a,i)=><div className="scout-tell" key={a}><strong>{String(i+1).padStart(2,'0')} · </strong>{a}</div>)}</div><div className="callout" style={{marginTop:12}}><Activity /> Validate automatic tells against film before installing game-plan calls.</div></Slide>
      <Slide number={9} title="Key Explosive Plays" subtitle="12+ yard gains from the selected Scout File"><MiniTable headers={['Play','Situation','Formation','Call','Gain']} rows={explosive.slice(0,12).map(p=>[`#${p.playNo}`,`${p.dn}&${p.dist} · ${p.hash}`,clean(p.form),clean(p.offPlay),p.gnls])}/></Slide>
      <div className="scout-slide-action"><button className="btn btn-primary" onClick={() => window.print()}><Printer /> Print / Save as PDF</button></div>
    </div>}
  </>;
}
